sylius_shop_cart_save:
    path: /
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.order:saveAction
        _sylius:
            template: "@SyliusShop/Cart/summary.html.twig"
            redirect: sylius_shop_cart_summary
            form: Sylius\Bundle\OrderBundle\Form\Type\CartType
            flash: sylius.cart.save