services:
  # Payment percentage discount action command
  sylius.promotion_action.payment_percentage_discount:
    class: AppBundle\Helpers\Promotion\PaymentPercentageDiscountPromotionActionCommand
    tags: 
      - { name: sylius.promotion_action, type: payment_percentage_discount, label: sylius.form.promotion_action.payment_percentage_discount, form_type: Sylius\Bundle\PromotionBundle\Form\Type\Action\PercentageDiscountConfigurationType, form-type: Sylius\Bundle\PromotionBundle\Form\Type\Action\PercentageDiscountConfigurationType }
    arguments: [ '@sylius.custom_factory.adjustment' ]  