sylius_grid:
    grids:
        app_admin_manufacturer:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Manufacturer
            fields:
                image:
                    type: twig
                    label: app.ui.logo_image
                    path: .
                    options:
                        template: "@App/Manufacturer/_image.html.twig"

                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                slug:
                    type: string
                    label: sylius.ui.slug
                    sortable: translation.slug
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                filterable:
                    type: twig
                    label: sylius.ui.filterable
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete