doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        server_version: "5.5"
        charset: UTF8
    orm:
        dql:
            numeric_functions:
                Rand: AppBundle\Helpers\Doctrine\RandFunction
            string_functions:
                MATCH_AGAINST: AppBundle\Helpers\Doctrine\MatchAgainst

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations