# GTM           
google_tag_manager:
    enabled: true
    id: "%gtm_id%"
    autoAppend: false
gtm:
    inject: true
    features:
        environment: true
        route: true
        context: true
        events: true