fos_sylius_import_export:
    importer:
        # set to false to not add an upload form to the entity overview pages
        web_ui:               false
        # set to an integer value to flush the object manager in regular intervals
        batch_size:           5
        # if incomplete rows (ie. missing required fields) should be considered failures
        fail_on_incomplete:   true
        # if to stop the import process in case of a failure
        stop_on_failure:      true