app_shop_partial_tag_show_by_slug:
    path: /tag-by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: app.controller.tag:showAction
        _sylius:
            template: $template
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
    requirements:
        slug: .+