app_admin_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusAdmin/Security/passwordRequest.html.twig"
            redirect: sylius_admin_login

app_admin_password_reset:
    path: /reset-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.admin_user:resetPasswordAction
        _sylius:
            template: "@SyliusAdmin/Security/passwordReset.html.twig"
            redirect: sylius_admin_login