winzou_state_machine:
    sylius_order_shipping:
        class: "%sylius.model.order.class%"
        property_path: shippingState
        graph: sylius_order_shipping
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            ready: ~
            issued_transport: ~
            shipped: ~
            cancelled: ~
        transitions:
            request_shipping:
                from: [cart]
                to: ready
            issue_transport:
                from: [ready]
                to: issued_transport
            ship:
                from: [issued_transport]
                to: shipped
            cancel:
                from: [ready]
                to: cancelled
        callbacks:
            after:
                sylius_resolve_state:
                    on: ["ship"]
                    do: ["@sylius.state_resolver.order", "resolve"]
                    args: ["object"]