app_admin_ajax_heureka_by_name_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: app.controller.heureka:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: $phrase

app_admin_ajax_heureka_by_id:
    path: /id
    methods: [GET]
    defaults:
        _controller: app.controller.heureka:indexAction
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [id: $id]