sylius_grid:
    grids:
        sylius_admin_product_attribute:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_attribute.class%"
            sorting:
                position: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                type:
                    type: twig
                    label: sylius.ui.type
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/ProductAttribute/Grid/Field/label.html.twig"
                filterable:
                    type: twig
                    label: sylius.ui.filterable
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
                position:
                    type: string
                    label: sylius.ui.position
                    sortable: ~
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create_product_attribute
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
