sylius_grid:
    grids:
        sylius_shop_manufacturer_products:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createShopManufacturerProductsQueryBuilder
                        arguments:
                            channel: "expr:service('sylius.context.channel').getChannel()"
                            manufacturer: "expr:notFoundOnNull(service('app.repository.manufacturer').findOneBySlug($slug, service('sylius.context.locale').getLocaleCode()))"
                            locale: "expr:service('sylius.context.locale').getLocaleCode()"
                            sorting: "expr:service('request_stack').getCurrentRequest().get('sorting', [])"
            limits: [9]
            fields:
                createdAt:
                    type: datetime
                    sortable: ~
                name:
                    type: string 
                    sortable: translation.name
                price:
                    type: int
                    sortable: channelPricing.price