AppBundle\Entity\PaymentMethod:
    properties:
        taxCategory:
            - NotBlank:
                groups: ["sylius"]
        price:
            - NotBlank:
                groups: ["sylius"]